require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Advise Hub' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false
  )

  # React Native Community packages
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'
  pod 'RNCClipboard', :path => '../node_modules/@react-native-community/clipboard'
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  # React Navigation
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # Other native modules
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end